/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Professor;

import Model.BO.ProfessorBO;
import Model.Data.ConexaoBanco;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author JVM
 */
public class ProfessorView extends javax.swing.JInternalFrame {
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form ProfessorView
     */
    public ProfessorView() {
        initComponents();
        Atualizar();
        
        rb_cls.setSelected(false);
        rb_cls.setVisible(false);
        
        bt_salvar.setEnabled(false);
    }
    
    //usado no botão salvar / editar
    //seta as informações
    ProfessorBO professorBO = new ProfessorBO();
    //usado no botão salvar / editar
    //seta as informações
    Model.Entity.Professor professor = new Model.Entity.Professor();
    
    //seto texto vazio para todos os campos
    public void LimpaTela(){
        txt_id.setText("");
        txt_nome.setText("");
        
        rb_masculino.setSelected(false);
        rb_feminino.setSelected(false);
        rb_cls.setSelected(true);
        
        txt_dnasc.setText("");
        txt_titulo.setText("");
        txt_salario.setText("");
        txt_telefone.setText("");
    }

    
    public void Atualizar(){
        try {
            String sql = "select * from professores";
            conn = ConexaoBanco.ConectaDB();
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tb_professores.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pn_cadastro = new javax.swing.JPanel();
        lb_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lb_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lb_sexo = new javax.swing.JLabel();
        rb_masculino = new javax.swing.JRadioButton();
        rb_feminino = new javax.swing.JRadioButton();
        rb_cls = new javax.swing.JRadioButton();
        lb_dnasc = new javax.swing.JLabel();
        txt_dnasc = new javax.swing.JTextField();
        lb_titulo = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        lb_salario = new javax.swing.JLabel();
        lb_telefone = new javax.swing.JLabel();
        txt_salario = new javax.swing.JTextField();
        bt_novo = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_excluir = new javax.swing.JButton();
        txt_telefone = new javax.swing.JTextField();
        pn_pesquisa = new javax.swing.JPanel();
        lb_pesquisar = new javax.swing.JLabel();
        txt_pesquisar = new javax.swing.JTextField();
        pn_table = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_professores = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);

        pn_cadastro.setBackground(new java.awt.Color(255, 255, 255));
        pn_cadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_id.setText("ID");

        txt_id.setEditable(false);

        lb_nome.setText("Nome");

        lb_sexo.setText("Sexo");

        buttonGroup1.add(rb_masculino);
        rb_masculino.setText("Masculino");
        rb_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_masculinoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_feminino);
        rb_feminino.setText("Feminino");
        rb_feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_femininoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_cls);

        lb_dnasc.setText("Data Nascimento");

        lb_titulo.setText("Titulo");

        lb_salario.setText("Salario");

        lb_telefone.setText("Telefone");

        bt_novo.setText("Novo");
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        bt_salvar.setText("Salvar");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        bt_editar.setText("Atualizar");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_excluir.setText("Excluir");
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_cadastroLayout = new javax.swing.GroupLayout(pn_cadastro);
        pn_cadastro.setLayout(pn_cadastroLayout);
        pn_cadastroLayout.setHorizontalGroup(
            pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_cadastroLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_dnasc)
                    .addComponent(lb_titulo)
                    .addComponent(lb_salario)
                    .addComponent(lb_sexo)
                    .addComponent(lb_id)
                    .addComponent(lb_nome)
                    .addComponent(lb_telefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_titulo)
                    .addComponent(txt_dnasc)
                    .addGroup(pn_cadastroLayout.createSequentialGroup()
                        .addComponent(rb_feminino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(rb_masculino))
                    .addComponent(txt_nome)
                    .addComponent(txt_id)
                    .addComponent(txt_salario)
                    .addComponent(txt_telefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_cls)
                .addGap(18, 18, 18)
                .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88))
        );
        pn_cadastroLayout.setVerticalGroup(
            pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cadastroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_cadastroLayout.createSequentialGroup()
                        .addComponent(bt_novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_excluir)
                        .addGap(45, 45, 45))
                    .addGroup(pn_cadastroLayout.createSequentialGroup()
                        .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_id)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_nome)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_sexo)
                            .addComponent(rb_cls)
                            .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rb_masculino)
                                .addComponent(rb_feminino)))
                        .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_dnasc)
                            .addComponent(txt_dnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_titulo)
                            .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_salario)
                            .addComponent(txt_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_telefone)
                            .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pn_pesquisa.setBackground(new java.awt.Color(255, 255, 255));
        pn_pesquisa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_pesquisar.setText("Pesquisar");

        txt_pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesquisarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pn_pesquisaLayout = new javax.swing.GroupLayout(pn_pesquisa);
        pn_pesquisa.setLayout(pn_pesquisaLayout);
        pn_pesquisaLayout.setHorizontalGroup(
            pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pesquisaLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lb_pesquisar)
                .addGap(46, 46, 46)
                .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_pesquisaLayout.setVerticalGroup(
            pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_pesquisaLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_pesquisar)
                    .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pn_table.setBackground(new java.awt.Color(255, 255, 255));
        pn_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tb_professores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_professores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_professoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_professores);

        javax.swing.GroupLayout pn_tableLayout = new javax.swing.GroupLayout(pn_table);
        pn_table.setLayout(pn_tableLayout);
        pn_tableLayout.setHorizontalGroup(
            pn_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        pn_tableLayout.setVerticalGroup(
            pn_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_tableLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_table, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_femininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_femininoActionPerformed
        sexo = "Feminino";
    }//GEN-LAST:event_rb_femininoActionPerformed

    private void rb_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_masculinoActionPerformed
        sexo = "Masculino";
    }//GEN-LAST:event_rb_masculinoActionPerformed

    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed
        LimpaTela();
        
        bt_salvar.setEnabled(true);
        bt_editar.setEnabled(false);
        bt_excluir.setEnabled(false);
        bt_novo.setEnabled(false);
    }//GEN-LAST:event_bt_novoActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        professor.setNome(txt_nome.getText());
        professor.setSexo(sexo);
        professor.setdNasc(txt_dnasc.getText());
        professor.setTitulo(txt_titulo.getText());
        professor.setSalario(txt_salario.getText());
        professor.setTelefone(txt_telefone.getText());

        //validações dos campos de inserção de informação
        //recebo os textos informados nos campos e jogo para variaveis
        String valida_nome = txt_nome.getText();
        String valida_dnasc = txt_dnasc.getText();
        String valida_titulo = txt_titulo.getText();
        String valida_salario = txt_salario.getText();
        String valida_telefone = txt_telefone.getText();

        if(valida_nome.equals("")){
            JOptionPane.showMessageDialog(null, "Insira o campo NOME");
        }else if( sexo == null){
            JOptionPane.showMessageDialog(null, "Selecione o SEXO - Masculino ou Feminino");
        }else if( valida_dnasc.equals("")){
            JOptionPane.showMessageDialog(null, "Selecione a DATA DE NASCIMENTO");
        }else if( valida_titulo.equals("")){
            JOptionPane.showMessageDialog(null, "Insira o campo TITULO DE GRADUACAO");
        }else if( valida_salario.equals("")){
            JOptionPane.showMessageDialog(null, "Insira o SALARIO");
        }else if( valida_telefone.equals("")){
            JOptionPane.showMessageDialog(null, "Selecione o TELEFONE");
        }else{//fim das validações dos campos de inserção de informação

            professorBO.CadastrarProfessores(professor);
            LimpaTela();
            Atualizar();
        }
        
        bt_salvar.setEnabled(false);
        bt_editar.setEnabled(true);
        bt_excluir.setEnabled(true);
        bt_novo.setEnabled(true);
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        professor.setNome(txt_nome.getText());
        professor.setSexo(sexo);
        professor.setdNasc(txt_dnasc.getText());
        professor.setTitulo(txt_titulo.getText());
        professor.setSalario(txt_salario.getText());
        professor.setTelefone(txt_telefone.getText());
        professor.setId(txt_id.getText());

        professorBO.EditarProfessor(professor);
        Atualizar();
        LimpaTela();
        
        
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Deseja Excluir esse Cadastro?");

        if (op == 0) {
            professor.setId(txt_id.getText());
            professorBO.RemoverProfessor(professor);

            Atualizar();
            LimpaTela();
        }
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void txt_pesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisarKeyReleased
         String sql = "select * from professores where nome like ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_pesquisar.getText()+"%");
            rs = pst.executeQuery();
            tb_professores.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
        bt_salvar.setEnabled(false);
        bt_editar.setEnabled(true);
        bt_excluir.setEnabled(true);
        bt_novo.setEnabled(true);
    }//GEN-LAST:event_txt_pesquisarKeyReleased

    private void tb_professoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_professoresMouseClicked
        int linha = tb_professores.getSelectedRow();
        String aoClicar = (tb_professores.getModel().getValueAt(linha, 0).toString());

        try {
            String sql = "select * from professores where id = '"+aoClicar+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if(rs.next()){
                String professor_id = rs.getString("id");
                txt_id.setText(professor_id);

                String professor_nome = rs.getString("nome");
                txt_nome.setText(professor_nome);

                //restauração do radio button de sexo selecionado
                String professor_sexo = rs.getString("sexo");

                if("Masculino".equals(professor_sexo)){
                    rb_masculino.setSelected(true);
                }

                if("Feminino".equals(professor_sexo)){
                    rb_feminino.setSelected(true);
                }
                //fim do radio button de sexo selecionado

                String professor_nascimento = rs.getString("dnascimento");
                txt_dnasc.setText(professor_nascimento);

                String professor_titulo = rs.getString("titulo");
                txt_titulo.setText(professor_titulo);

                String professor_salario = rs.getString("salario");
                txt_salario.setText(professor_salario);

                String professor_telefone = rs.getString("telefone");
                txt_telefone.setText(professor_telefone);
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
        bt_salvar.setEnabled(false);
        bt_editar.setEnabled(true);
        bt_excluir.setEnabled(true);
        bt_novo.setEnabled(true);
    }//GEN-LAST:event_tb_professoresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_novo;
    private javax.swing.JButton bt_salvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_dnasc;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_pesquisar;
    private javax.swing.JLabel lb_salario;
    private javax.swing.JLabel lb_sexo;
    private javax.swing.JLabel lb_telefone;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JPanel pn_cadastro;
    private javax.swing.JPanel pn_pesquisa;
    private javax.swing.JPanel pn_table;
    private javax.swing.JRadioButton rb_cls;
    private javax.swing.JRadioButton rb_feminino;
    private javax.swing.JRadioButton rb_masculino;
    private javax.swing.JTable tb_professores;
    private javax.swing.JTextField txt_dnasc;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_pesquisar;
    private javax.swing.JTextField txt_salario;
    private javax.swing.JTextField txt_telefone;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
    String sexo = null;
}
