/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Aluno;

import Model.BO.AlunoBO;
import Model.Data.ConexaoBanco;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author JVM
 */

public class AlunoView extends javax.swing.JInternalFrame {
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form AlunoView
     */
    public AlunoView() {
        initComponents();
        
        //initComponents();
        Atualizar();

        rb_cls.setSelected(false);
        rb_cls.setVisible(false);
        
        bt_salvar.setEnabled(false);
    }
    
    //usado no botão salvar / editar
    //seta as informações
    AlunoBO alunoBO = new AlunoBO();
    //usado no botão salvar / editar
    //seta as informações
    Model.Entity.Aluno aluno = new Model.Entity.Aluno();
    
    //Metodo de limpa tela, botão novo
    //seto texto vazio para todos os campos
    public void LimpaTela(){
        txt_id.setText("");
        txt_nome.setText("");
        
        rb_masculino.setSelected(false);
        rb_feminino.setSelected(false);
        rb_cls.setSelected(true);
        
        txt_dnasc.setText("");
        txt_matricula.setText("");
        txt_curso.setText("");
        txt_email.setText("");
    }
    
    //Metodo que atualiza a tabela
    public void Atualizar(){
        try {
            String sql = "select * from alunos";
            conn = ConexaoBanco.ConectaDB();
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tb_alunos.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pn_cadastro = new javax.swing.JPanel();
        lb_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lb_sexo = new javax.swing.JLabel();
        rb_masculino = new javax.swing.JRadioButton();
        rb_feminino = new javax.swing.JRadioButton();
        lb_dnasc = new javax.swing.JLabel();
        txt_dnasc = new javax.swing.JTextField();
        lb_matricula = new javax.swing.JLabel();
        txt_matricula = new javax.swing.JTextField();
        lb_curso = new javax.swing.JLabel();
        txt_curso = new javax.swing.JTextField();
        lb_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lb_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        rb_cls = new javax.swing.JRadioButton();
        bt_novo = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_excluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_alunos = new javax.swing.JTable();
        pn_pesquisa = new javax.swing.JPanel();
        lb_pesquisar = new javax.swing.JLabel();
        txt_pesquisar = new javax.swing.JTextField();

        setClosable(true);

        pn_cadastro.setBackground(new java.awt.Color(255, 255, 255));
        pn_cadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_nome.setText("Nome");

        lb_sexo.setText("Sexo");

        buttonGroup1.add(rb_masculino);
        rb_masculino.setText("Masculino");
        rb_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_masculinoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_feminino);
        rb_feminino.setText("Feminino");
        rb_feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_femininoActionPerformed(evt);
            }
        });

        lb_dnasc.setText("Data Nascimento");

        lb_matricula.setText("Matricula");

        lb_curso.setText("Curso");

        lb_id.setText("ID");

        txt_id.setEditable(false);

        lb_email.setText("Email");

        buttonGroup1.add(rb_cls);

        bt_novo.setText("Novo");
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        bt_salvar.setText("Salvar");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        bt_editar.setText("Atualizar");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_excluir.setText("Remover");
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_cadastroLayout = new javax.swing.GroupLayout(pn_cadastro);
        pn_cadastro.setLayout(pn_cadastroLayout);
        pn_cadastroLayout.setHorizontalGroup(
            pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cadastroLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_email)
                    .addComponent(lb_id)
                    .addComponent(lb_curso)
                    .addComponent(lb_matricula)
                    .addComponent(lb_dnasc)
                    .addComponent(lb_sexo)
                    .addComponent(lb_nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pn_cadastroLayout.createSequentialGroup()
                        .addComponent(rb_feminino)
                        .addGap(8, 8, 8)
                        .addComponent(rb_masculino))
                    .addComponent(txt_id)
                    .addComponent(txt_nome)
                    .addComponent(txt_dnasc)
                    .addComponent(txt_matricula)
                    .addComponent(txt_curso)
                    .addComponent(txt_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_cls)
                .addGap(18, 18, 18)
                .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_salvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 115, Short.MAX_VALUE))
        );
        pn_cadastroLayout.setVerticalGroup(
            pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cadastroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_cadastroLayout.createSequentialGroup()
                        .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_id)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_nome)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bt_novo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_cadastroLayout.createSequentialGroup()
                        .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_cls)
                            .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lb_sexo)
                                .addComponent(rb_masculino)
                                .addComponent(rb_feminino)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_dnasc)
                            .addComponent(txt_dnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_matricula)
                            .addComponent(txt_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_editar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_curso)
                            .addComponent(txt_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_email)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_excluir)))
                    .addComponent(bt_salvar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tb_alunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_alunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_alunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_alunos);

        pn_pesquisa.setBackground(new java.awt.Color(255, 255, 255));
        pn_pesquisa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_pesquisar.setText("Pesquisar");

        txt_pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesquisarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pn_pesquisaLayout = new javax.swing.GroupLayout(pn_pesquisa);
        pn_pesquisa.setLayout(pn_pesquisaLayout);
        pn_pesquisaLayout.setHorizontalGroup(
            pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pesquisaLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lb_pesquisar)
                .addGap(18, 18, 18)
                .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_pesquisaLayout.setVerticalGroup(
            pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_pesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_pesquisar)
                    .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(pn_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_masculinoActionPerformed
        sexo = "Masculino";
    }//GEN-LAST:event_rb_masculinoActionPerformed

    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed
        LimpaTela();
        
        bt_salvar.setEnabled(true);
        bt_editar.setEnabled(false);
        bt_excluir.setEnabled(false);
        bt_novo.setEnabled(false);
    }//GEN-LAST:event_bt_novoActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        aluno.setNome(txt_nome.getText());
        aluno.setSexo(sexo);
        aluno.setdNasc(txt_dnasc.getText());
        aluno.setMatricula(txt_matricula.getText());
        aluno.setCurso(txt_curso.getText());
        aluno.setEmail(txt_email.getText());

        //validações dos campos de inserção de informação
        //recebo os textos informados nos campos e jogo para variaveis
        String valida_nome = txt_nome.getText();
        String valida_dnasc = txt_dnasc.getText();
        String valida_matricula = txt_matricula.getText();
        String valida_curso = txt_curso.getText();
        String valida_semestre = txt_matricula.getText();
        String valida_email = txt_email.getText();

        if(valida_nome.equals("")){
            JOptionPane.showMessageDialog(null, "Insira o campo NOME");
        }else if( sexo == null){
            JOptionPane.showMessageDialog(null, "Selecione o SEXO - Masculino ou Feminino");
        }else if( valida_dnasc.equals("")){
            JOptionPane.showMessageDialog(null, "Selecione a DATA DE NASCIMENTO");
        }else if( valida_matricula.equals("")){
            JOptionPane.showMessageDialog(null, "Insira o campo MATRICULA");
        }else if( valida_curso.equals("")){
            JOptionPane.showMessageDialog(null, "Insira o nome do CURSO");
        }else if( valida_email.equals("")){
            JOptionPane.showMessageDialog(null, "Selecione o EMAIL");
        }else{//fim das validações dos campos de inserção de informação

            alunoBO.CadastrarAluno(aluno);
            LimpaTela();
            Atualizar();
        }
        
        bt_salvar.setEnabled(false);
        bt_editar.setEnabled(true);
        bt_excluir.setEnabled(true);
        bt_novo.setEnabled(true);
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        aluno.setNome(txt_nome.getText());
        aluno.setSexo(sexo);
        aluno.setdNasc(txt_dnasc.getText());
        aluno.setMatricula(txt_matricula.getText());
        aluno.setCurso(txt_curso.getText());
        aluno.setEmail(txt_email.getText());
        aluno.setId(txt_id.getText());

        alunoBO.EditarAluno(aluno);
        Atualizar();
        LimpaTela();
        
        bt_salvar.setEnabled(false);
        bt_editar.setEnabled(true);
        bt_excluir.setEnabled(true);
        bt_novo.setEnabled(true);
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Deseja Excluir esse Cadastro?");

        if (op == 0) {
            aluno.setId(txt_id.getText());
            alunoBO.RemoverAluno(aluno);

            Atualizar();
            LimpaTela();
        }
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void txt_pesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisarKeyReleased
        String sql = "select * from alunos where nome like ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_pesquisar.getText()+"%");
            rs = pst.executeQuery();
            tb_alunos.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
        
        bt_salvar.setEnabled(false);
        bt_editar.setEnabled(true);
        bt_excluir.setEnabled(true);
        bt_novo.setEnabled(true);
    }//GEN-LAST:event_txt_pesquisarKeyReleased

    private void tb_alunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_alunosMouseClicked
        int linha = tb_alunos.getSelectedRow();
        String aoClicar = (tb_alunos.getModel().getValueAt(linha, 0).toString());

        try {
            String sql = "select * from alunos where id = '"+aoClicar+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if(rs.next()){
                String aluno_id = rs.getString("id");
                txt_id.setText(aluno_id);

                String aluno_nome = rs.getString("nome");
                txt_nome.setText(aluno_nome);

                //restauração do radio button de sexo selecionado
                String aluno_sexo = rs.getString("sexo");

                if("Masculino".equals(aluno_sexo)){
                    rb_masculino.setSelected(true);
                }

                if("Feminino".equals(aluno_sexo)){
                    rb_feminino.setSelected(true);
                }
                //fim do radio button de sexo selecionado

                String aluno_nascimento = rs.getString("dnascimento");
                txt_dnasc.setText(aluno_nascimento);

                String aluno_matricula = rs.getString("matricula");
                txt_matricula.setText(aluno_matricula);

                String aluno_curso = rs.getString("curso");
                txt_curso.setText(aluno_curso);

                String aluno_email = rs.getString("email");
                txt_email.setText(aluno_email);
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
        
        bt_salvar.setEnabled(false);
        bt_editar.setEnabled(true);
        bt_excluir.setEnabled(true);
        bt_novo.setEnabled(true);
    }//GEN-LAST:event_tb_alunosMouseClicked

    private void rb_femininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_femininoActionPerformed
        sexo = "Feminino";
    }//GEN-LAST:event_rb_femininoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_novo;
    private javax.swing.JButton bt_salvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_curso;
    private javax.swing.JLabel lb_dnasc;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_matricula;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_pesquisar;
    private javax.swing.JLabel lb_sexo;
    private javax.swing.JPanel pn_cadastro;
    private javax.swing.JPanel pn_pesquisa;
    private javax.swing.JRadioButton rb_cls;
    private javax.swing.JRadioButton rb_feminino;
    private javax.swing.JRadioButton rb_masculino;
    private javax.swing.JTable tb_alunos;
    private javax.swing.JTextField txt_curso;
    private javax.swing.JTextField txt_dnasc;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_matricula;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_pesquisar;
    // End of variables declaration//GEN-END:variables
    String sexo = null;
}
